### ISSUE TITLE
Some odd bugs and a crash

### ISSUE THREAD

**Issue by Carvercarver1** [TheCodex6824/ThaumcraftFix#14] opened 2024-07-07 14:03 UTC
Not sure exactly why it happens, but if you hover with the thaumometer onto the firebat it just straight up crashes the game due to GUI issues and aspects, making it so you cannot scan it properly and rejoin the world unless you relaunch the entire game.

Secondly, sometimes lightning focus effect does not seem to render, sometimes it does. Perhaps needs a safety feature for rendering the thing if it does not normally do. It works, it just misses the bolt itself apparently. I will report more as I play.

**Comment by TheCodex6824** [comment] 2024-07-07 21:03
For the particles, I haven't noticed bolts not rendering on a smallish test pack, so it might be Particle Culling as mentioned. The bats though are indeed a problem.

**Comment by TheCodex6824** [comment] 2024-07-08 00:42
> I was told that the thaumometer firebat crash had to do with [another addon](https://github.com/Zokonius/planar-artifice/issues/91), I wouldn't fault vanilla Thaumcraft for this one.

Oh - if it's trying to assign aspects that don't exist to it then yeah, I don't think that's Thaumcraft's fault. I can't really do much about addons making questionable decisions.

**Comment by KELETU66666** [comment] 2024-07-09 14:39
> I was told that the thaumometer firebat crash had to do with [another addon](https://github.com/Zokonius/planar-artifice/issues/91), I wouldn't fault vanilla Thaumcraft for this one.

this bug caused by author of PA don't needs thaumic additions as its requirement.

**Comment by TheCodex6824** [comment] 2024-07-10 00:03
Since it seems like the only issue caused by Thaumcraft itself here (other than maybe having bad particle bounding boxes) is the spellbat spawn egg which got fixed, I'm going to close this. The firebat issue as mentioned before is caused by other addons.

**Closed by TheCodex6824** 2024-07-10 00:03 UTC
Labels: Thaumcraft Bug
